export const lightTheme = [
  "--background-app: #f3f7fa",
  "--body-text: #4A4A4A",
  "--box-shadow: rgba(0, 0, 0, 0.1)",
  "--filter-background: #fff",
  "--filter-hover-item: #F1FCFF",
  "--filter-text: #4A4A4A",
  "--checkbox-box: rgba(154, 187, 206, 1)",
  "--checkbox-box-check: #2196F3",
  "--sorting-tab-background: #fff",
  "--sorting-tab-background-active: #2196F3",
  "--sorting-tab-background-hover: #F1FCFF",
  "--sorting-tab-text: #4A4A4A",
  "--sorting-tab-text-active: #fff",
  "--sorting-tab-text-hover: #2196F3",
  "--sorting-tab-border: #DFE5EC",
  "--sorting-tab-border-hover: #2196F3",
  "--ticket-background: #fff",
  "--ticket-price: #2196F3",
  "--ticket-text-subtitle: #A0B0B9",
  "--ticket-text: #4A4A4A"
];

export const darkTheme = [
  "--background-app: #05263f",
  "--body-text: #fff",
  "--box-shadow: rgba(0, 0, 0, 0.1)",
  "--filter-background: #1e3c52",
  "--filter-hover-item: #355064",
  "--filter-text: #fff",
  "--checkbox-box: rgba(154, 187, 206, 1)",
  "--checkbox-box-check: #2196F3",
  "--sorting-tab-background: #1e3c52",
  "--sorting-tab-background-active: #2196f3",
  "--sorting-tab-background-hover: #031b2c",
  "--sorting-tab-text: #fff",
  "--sorting-tab-text-active: #fff",
  "--sorting-tab-text-hover: #fff",
  "--sorting-tab-border: #000",
  "--sorting-tab-border-hover: #000",
  "--ticket-background: #1e3c52",
  "--ticket-price: #f57c00",
  "--ticket-text-subtitle: #A0B0B9",
  "--ticket-text: #fff"
];
